# Generated by Django 4.2.3 on 2023-08-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Tel',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
