# Generated by Django 4.2.3 on 2023-08-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonApp', '0002_message_tel_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Tel',
            field=models.IntegerField(default=0),
        ),
    ]
