# Generated by Django 4.2.3 on 2023-08-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonApp', '0004_alter_message_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Tel',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
