# Generated by Django 4.2.3 on 2023-08-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonApp', '0007_message_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Tel',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
