# Generated by Django 4.2.3 on 2023-08-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonApp', '0008_alter_message_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Tel',
            new_name='Telephone',
        ),
    ]
