# Generated by Django 4.2.3 on 2023-08-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonApp', '0009_rename_tel_message_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('Nom', models.CharField(max_length=20)),
                ('Mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=1000)),
                ('Tel', models.CharField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
