# Generated by Django 4.2.3 on 2023-08-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonApp', '0010_commentaire_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='Tel',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
