# Generated by Django 4.2.5 on 2023-09-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonApp', '0011_alter_commentaire_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='Mail',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='Nom',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='Tel',
            field=models.CharField(max_length=13, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Message'),
        ),
    ]
