# Generated by Django 4.2.5 on 2023-09-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonApp', '0012_alter_commentaire_mail_alter_commentaire_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='Nom',
            field=models.CharField(help_text='Enter your name', max_length=20, verbose_name='Name'),
        ),
    ]
