# Generated by Django 4.2.5 on 2023-09-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonApp', '0013_alter_commentaire_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='Nom',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
