# Generated by Django 4.2.5 on 2023-09-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonAppManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='status',
            field=models.CharField(default='livre', max_length=20),
            preserve_default=False,
        ),
    ]
