# Generated by Django 4.2.5 on 2023-09-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonAppManagement', '0003_alter_userinformations_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='status',
            field=models.CharField(choices=[('T', 'traité'), ('N', 'Non traité')], max_length=20),
        ),
    ]
