# Generated by Django 4.2.5 on 2023-09-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonAppManagement', '0004_alter_userinformations_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformations',
            name='status',
        ),
    ]
