# Generated by Django 4.2.5 on 2023-09-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonAppManagement', '0005_remove_userinformations_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='status',
            field=models.CharField(choices=[('T', 'traité'), ('N', 'Non traité')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
